project_id = "kcunskgjvmzrxenjblmk"

[functions.create-order]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-tracking-email]
verify_jwt = false

[functions.sales-stats]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.get-order-details]
verify_jwt = false

[functions.generate-product-content]
verify_jwt = false

[functions.generate-category-banner]
verify_jwt = false

[functions.generate-promotional-banner]
verify_jwt = false
