project_id = "kcunskgjvmzrxenjblmk"

[functions.create-order]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-tracking-email]
verify_jwt = false

[functions.sales-stats]
verify_jwt = false
